discovery-servers:
    nacos1:
        type: nacos
        weight: 100
        prefix: /nacos/v1/
        host: "http://nacos-server:8858"
    eureka1:
        type: eureka
        weight: 100
        prefix: /eureka/
        host: "http://admin:admin@eureka-server:8761"

gateway-servers:
    apisix1:
        type: apisix
        admin-url: http://apisix-server:9080
        prefix: /apisix/admin/
        config:
            X-API-KEY: edd1c9f034335f136f87ad84b625c8f1
            version: v3
    kong1:
        type: kong
        admin-url: http://kong-server:8001
        prefix: /upstreams/
        config:
            targets_uri: /targets/all

targets:
    -   discovery: nacos1
        gateway: apisix1
        enabled: false
        fetch-interval: "*/30 * * * * *" # every 30 seconds
        maximum-interval-sec: 20 # now - last > ${maximum-interval-sec}sec is lost
        upstream-prefix: test
        name: test
        config:
            groupName: DEFAULT_GROUP
            namespaceId: test
            template: |
                {
                    "id": "$name",
                    "timeout": {
                        "connect": 30,
                        "send": 30,
                        "read": 30
                    },
                    "name": "$name",
                    "nodes": $nodes,
                    "type":"roundrobin",
                    "desc": "auto sync by https://github.com/anjia0532/discovery-syncer-python"
                }

    -   discovery: eureka1
        gateway: apisix1
        enabled: false
        fetch-interval: "*/10 * * * * *" # every 10 seconds
        upstream-prefix: test-eureka
        name: test-eureka
        maximum-interval-sec: 10
        config:
            template: |
                {
                    "name": "$name",
                    "algorithm": "round-robin",
                    "hash_on": "none",
                    "hash_fallback": "none",
                    "hash_on_cookie_path": "/",
                    "slots": 10000,
                    "healthchecks": {
                        "passive": {
                            "healthy": {
                                "http_statuses": [200, 201, 202, 203, 204, 205, 206, 207, 208, 226, 300, 301, 302, 303, 304, 305, 306, 307, 308],
                                "successes": 0
                            },
                            "type": "http",
                            "unhealthy": {
                                "http_statuses": [429, 500, 503],
                                "timeouts": 0,
                                "http_failures": 0,
                                "tcp_failures": 0
                            }
                        },
                        "active": {
                            "timeout": 1,
                            "https_sni": "example.com",
                            "http_path": "/",
                            "concurrency": 10,
                            "https_verify_certificate": true,
                            "type": "http",
                            "healthy": {
                                "http_statuses": [200, 302],
                                "successes": 0,
                                "interval": 0
                            },
                            "unhealthy": {
                                "http_statuses": [429, 404, 500, 501, 502, 503, 504, 505],
                                "timeouts": 0,
                                "http_failures": 0,
                                "interval": 0,
                                "tcp_failures": 0
                            }
                        },
                        "threshold": 0
                    },
                    "tags": ["discovery-syncer-auto"]
                }
